# This is a config for E2B sandbox template.
# You can use template ID (86a6djcv83utkbkt852p) or template name (vibe-coder-nextjs-test-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-coder-nextjs-test-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-coder-nextjs-test-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-coder-nextjs-test-2')

team_id = "e7cd3b9b-d1e1-4bc5-b02c-d1f217f81cd7"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-coder-nextjs-test-2"
template_id = "86a6djcv83utkbkt852p"
